
-- Insert sample recipes from the CSV data
-- Note: This is a small sample - in production you'd bulk import the full CSV

INSERT INTO recipes (
  title, description, ingredients, instructions, prep_time, cook_time, servings,
  dosha_effects, thermal_effect, weight_effect, recommended_doshas, seasonal_suitability,
  difficulty_level, calories_per_serving, image_url, rating, rating_count, created_by,
  preparation_tips, health_benefits
) VALUES 
(
  'Mung Bean Khichdi',
  'A nourishing and easily digestible one-pot meal perfect for balancing Vata and Pitta doshas',
  '["Mung dal", "rice", "ghee", "turmeric", "cumin"]',
  'Boil rice and mung dal together until soft. Season with ghee and spices. Serve hot.',
  15, 25, 4,
  '{"vata": "balancing", "pitta": "cooling", "kapha": "neutral"}',
  'neutral', 'light',
  '["vata", "pitta"]',
  '["autumn", "winter", "spring"]',
  'easy', 350,
  'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400',
  4.7, 89, 'Traditional Ayurveda',
  'Soak mung dal for 30 minutes before cooking for better digestibility',
  'Easy to digest, balances doshas, provides complete protein'
),
(
  'Carrot Halwa',
  'A warming dessert that improves digestion and provides natural energy',
  '["Carrots", "milk", "ghee", "jaggery", "cardamom"]',
  'Grate carrots and cook in milk until tender. Add ghee and jaggery, cook until thick.',
  20, 30, 6,
  '{"vata": "nourishing", "pitta": "neutral", "kapha": "increasing"}',
  'warming', 'heavy',
  '["kapha", "vata"]',
  '["winter", "autumn"]',
  'medium', 251,
  'https://images.unsplash.com/photo-1571197777636-c1b5d8a6b27a?w=400',
  4.5, 156, 'North Indian Kitchen',
  'Use fresh cardamom powder for best flavor',
  'Improves digestion, energizing, rich in beta-carotene'
),
(
  'Turmeric Milk',
  'Golden milk with anti-inflammatory properties, perfect before bedtime',
  '["Milk", "turmeric", "black pepper", "honey"]',
  'Heat milk gently, whisk in turmeric and black pepper. Add honey to taste.',
  5, 10, 1,
  '{"vata": "calming", "pitta": "neutral", "kapha": "reducing"}',
  'warming', 'light',
  '["vata", "kapha"]',
  '["winter", "autumn", "spring"]',
  'easy', 122,
  'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400',
  4.8, 245, 'Ayurvedic Kitchen',
  'A pinch of black pepper enhances turmeric absorption',
  'Anti-inflammatory, boosts immunity, promotes restful sleep'
),
(
  'Ashwagandha Ladoo',
  'Energy-boosting sweet balls that help reduce stress and promote vitality',
  '["Ashwagandha powder", "ghee", "jaggery", "almonds"]',
  'Mix ashwagandha powder with melted ghee and jaggery. Add chopped almonds and shape into balls.',
  15, 0, 20,
  '{"vata": "deeply nourishing", "pitta": "neutral", "kapha": "neutral"}',
  'warming', 'heavy',
  '["vata"]',
  '["autumn", "winter"]',
  'easy', 183,
  'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400',
  4.6, 128, 'Ayurvedic Wellness',
  'Store in airtight container for up to 2 weeks',
  'Reduces stress, promotes vitality, strengthens nervous system'
),
(
  'Spinach Dal',
  'Iron-rich lentil curry with fresh spinach, perfect for building strength',
  '["Spinach", "yellow dal", "ghee", "garlic", "spices"]',
  'Cook dal until soft. Add chopped spinach and season with garlic and spices.',
  10, 20, 4,
  '{"vata": "neutral", "pitta": "cooling", "kapha": "light"}',
  'neutral', 'medium',
  '["pitta", "kapha"]',
  '["spring", "summer"]',
  'medium', 224,
  'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
  4.4, 203, 'South Indian Kitchen',
  'Add spinach in the last 5 minutes to retain nutrients',
  'Iron-rich, strengthens blood and immunity, easily digestible'
),
(
  'Coconut Chutney',
  'Cooling South Indian condiment perfect for Pitta constitution',
  '["Fresh coconut", "green chilies", "ginger", "curry leaves", "mustard seeds"]',
  'Grind coconut with chilies and ginger. Temper with mustard seeds and curry leaves.',
  15, 5, 4,
  '{"vata": "nourishing", "pitta": "cooling", "kapha": "neutral"}',
  'cooling', 'medium',
  '["pitta", "vata"]',
  '["summer", "spring"]',
  'easy', 95,
  'https://images.unsplash.com/photo-1589638147634-3c4de85ca6aa?w=400',
  4.3, 167, 'Kerala Kitchen',
  'Use fresh coconut for best taste and nutrition',
  'Cooling effect, aids digestion, provides healthy fats'
),
(
  'Ginger Tea',
  'Warming digestive tea that kindles digestive fire',
  '["Fresh ginger", "water", "honey", "lemon"]',
  'Boil sliced ginger in water for 10 minutes. Strain, add honey and lemon.',
  5, 10, 2,
  '{"vata": "warming", "pitta": "mild", "kapha": "stimulating"}',
  'heating', 'light',
  '["vata", "kapha"]',
  '["winter", "autumn", "spring"]',
  'easy', 25,
  'https://images.unsplash.com/photo-1597318756612-cf222d9fb86b?w=400',
  4.7, 234, 'Traditional Medicine',
  'Add honey only after tea cools slightly to preserve its properties',
  'Improves digestion, reduces nausea, boosts circulation'
),
(
  'Quinoa Upma',
  'Light breakfast dish with warming spices, suitable for Kapha reduction',
  '["Quinoa", "vegetables", "mustard seeds", "curry leaves", "turmeric"]',
  'Dry roast quinoa. Heat oil, add mustard seeds and curry leaves. Add quinoa and vegetables.',
  10, 20, 4,
  '{"vata": "neutral", "pitta": "neutral", "kapha": "reducing"}',
  'warming', 'light',
  '["kapha", "vata"]',
  '["spring", "winter"]',
  'medium', 185,
  'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400',
  4.2, 89, 'Modern Ayurveda',
  'Toast quinoa lightly for better flavor and digestibility',
  'Light, protein-rich, reduces Kapha, gluten-free'
);