
-- Insert sample face packs
INSERT INTO face_packs (name, description, ingredients, preparation_method, application_instructions, benefits, skin_type, dosha_suitability, preparation_time, application_duration, frequency, precautions, difficulty_level) VALUES
('Turmeric Honey Glow Pack', 'Natural antibacterial face pack for glowing skin', '1 tsp turmeric powder, 2 tbsp raw honey, 1 tsp rose water', 'Mix turmeric powder with honey until smooth. Add rose water gradually to form a paste.', 'Apply evenly on clean face, avoiding eye area. Leave for 15-20 minutes.', 'Reduces acne, Brightens skin, Anti-inflammatory, Natural glow', 'All skin types', 'Pitta, Kapha', 5, 20, '2-3 times per week', 'Patch test before use. May cause temporary yellow tint.', 'Easy'),
('Oatmeal Milk Exfoliating Pack', 'Gentle exfoliating pack for smooth, soft skin', '3 tbsp oatmeal powder, 2 tbsp milk, 1 tsp honey', 'Grind oats to fine powder. Mix with milk and honey to form thick paste.', 'Gently massage in circular motions, then leave for 10 minutes before rinsing.', 'Gentle exfoliation, Moisturizes skin, Removes dead cells, Softens skin', 'Dry, Sensitive', 'Vata, Pitta', 8, 15, 'Once a week', 'Avoid if allergic to dairy. Use lukewarm water to rinse.', 'Easy'),
('Neem Fuller Earth Acne Pack', 'Powerful acne-fighting pack with natural antibacterials', '2 tbsp neem powder, 2 tbsp fuller earth, 1 tbsp rose water', 'Mix neem powder and fuller earth. Add rose water slowly to make smooth paste.', 'Apply thick layer on affected areas. Let dry completely before washing off.', 'Fights acne, Controls oil, Purifies skin, Reduces inflammation', 'Oily, Acne-prone', 'Pitta, Kapha', 5, 25, '2 times per week', 'May cause dryness. Follow with moisturizer.', 'Easy'),
('Cucumber Aloe Cooling Pack', 'Refreshing pack for irritated and inflamed skin', '1 small cucumber, 2 tbsp fresh aloe vera gel, 1 tsp rose water', 'Blend cucumber to paste. Mix with aloe vera gel and rose water.', 'Apply generously and leave for 20 minutes. Rinse with cool water.', 'Soothes inflammation, Hydrates skin, Cooling effect, Reduces puffiness', 'Sensitive, Irritated', 'Pitta', 10, 20, '3-4 times per week', 'Use fresh ingredients only. Store in refrigerator.', 'Easy'),
('Papaya Honey Anti-Aging Pack', 'Enzyme-rich pack for youthful, radiant skin', '4-5 papaya pieces, 1 tbsp honey, 1 tsp lemon juice', 'Mash papaya to smooth paste. Mix with honey and lemon juice.', 'Apply evenly, avoiding eyes. Leave for 15 minutes before rinsing.', 'Reduces fine lines, Brightens complexion, Natural enzymes, Anti-aging', 'Normal, Mature', 'All doshas', 8, 15, 'Once a week', 'Avoid sun exposure after use due to lemon.', 'Easy'),
('Sandalwood Rose Water Pack', 'Classic Ayurvedic pack for calm, glowing skin', '2 tbsp sandalwood powder, 3 tbsp rose water, 1 tsp honey', 'Mix sandalwood powder with rose water to form smooth paste. Add honey.', 'Apply thin layer and let dry for 20 minutes. Rinse with lukewarm water.', 'Calms skin, Natural fragrance, Reduces blemishes, Cooling effect', 'All skin types', 'Pitta, Vata', 5, 20, '2 times per week', 'Use pure sandalwood powder only.', 'Easy'),
('Besan Yogurt Brightening Pack', 'Traditional gram flour pack for fair and bright skin', '3 tbsp besan, 2 tbsp plain yogurt, Pinch of turmeric', 'Mix besan with yogurt to form lump-free paste. Add turmeric.', 'Apply evenly and let dry. Gently scrub off with wet hands.', 'Natural bleaching, Removes tan, Gentle exfoliation, Oil control', 'Oily, Combination', 'Kapha, Pitta', 5, 20, '2-3 times per week', 'May cause dryness for very dry skin.', 'Easy'),
('Avocado Banana Moisturizing Pack', 'Rich nourishing pack for dry and dull skin', '1/2 ripe avocado, 1/2 ripe banana, 1 tbsp olive oil', 'Mash avocado and banana together. Mix in olive oil until creamy.', 'Apply thick layer and relax for 20 minutes. Rinse with warm water.', 'Deep moisturizing, Natural oils, Vitamin rich, Soft skin', 'Dry, Very dry', 'Vata', 8, 20, 'Once a week', 'Use immediately after preparation.', 'Easy'),
('Tomato Sugar Scrub Pack', 'Natural exfoliating pack with vitamin C', '1 large tomato, 2 tbsp brown sugar, 1 tsp olive oil', 'Blend tomato to pulp. Mix with sugar and olive oil.', 'Gently massage for 2 minutes, then leave for 10 minutes.', 'Natural vitamin C, Gentle exfoliation, Brightens skin, Removes blackheads', 'Normal, Oily', 'Pitta, Kapha', 7, 12, 'Once a week', 'Avoid if sensitive to acids.', 'Easy'),
('Mint Honey Refreshing Pack', 'Cooling and refreshing pack for tired skin', '10-12 fresh mint leaves, 2 tbsp honey, 1 tbsp rose water', 'Crush mint leaves and mix with honey and rose water.', 'Apply and leave for 15 minutes. Rinse with cool water.', 'Refreshes skin, Natural coolant, Antibacterial, Invigorating', 'All skin types', 'Pitta', 6, 15, '2 times per week', 'Use fresh mint only.', 'Easy');

-- Insert sample BAMS books
INSERT INTO bams_books (title, author, subject, year_of_study, semester, description, page_count, language, is_free, price, file_size_mb) VALUES
('Fundamental Principles of Ayurveda', 'Dr. Ramesh Sharma', 'Basic Principles', 1, 1, 'Comprehensive introduction to Ayurvedic principles, doshas, and basic concepts essential for BAMS students.', 320, 'English', 1, 0, 15.2),
('Anatomy and Physiology in Ayurveda', 'Dr. Priya Nair', 'Rachana Sharir', 1, 2, 'Detailed study of human anatomy and physiology from Ayurvedic perspective with modern correlations.', 450, 'English', 1, 0, 22.8),
('Dravyaguna Vigyan - Medicinal Plants', 'Dr. Anil Kumar', 'Dravyaguna', 2, 1, 'Complete guide to medicinal plants, their properties, and therapeutic applications in Ayurveda.', 380, 'English', 1, 0, 18.5),
('Advanced Panchakarma Therapy', 'Dr. Rajesh Kotecha', 'Panchakarma', 3, 2, 'In-depth study of Panchakarma procedures, indications, contraindications, and practical applications.', 520, 'English', 0, 99, 25.7),
('Ayurvedic Pathology & Diagnosis', 'Dr. Meera Patel', 'Rog Nidan', 2, 2, 'Comprehensive guide to disease diagnosis and pathology according to Ayurvedic principles.', 410, 'English', 0, 99, 20.3),
('Rasayana and Vajikarana Therapy', 'Dr. Suresh Babu', 'Rasayana', 4, 1, 'Study of rejuvenation and aphrodisiac therapies with practical formulations and applications.', 350, 'English', 0, 99, 16.8),
('Kayachikitsa - Internal Medicine', 'Dr. Vandana Singh', 'Kayachikitsa', 3, 1, 'Complete textbook on Ayurvedic internal medicine with case studies and treatment protocols.', 480, 'English', 0, 99, 23.9),
('Shalya Tantra - Ayurvedic Surgery', 'Dr. Mahesh Gupta', 'Shalya Tantra', 4, 2, 'Principles and practices of Ayurvedic surgery with modern surgical correlations.', 390, 'English', 0, 99, 19.2);

-- Insert sample herbal seeds
INSERT INTO herbal_seeds (name, scientific_name, common_names, plant_type, medicinal_properties, health_benefits, growing_instructions, climate_requirements, soil_type, watering_frequency, sunlight_requirements, harvest_time, usage_parts, preparation_methods, dosage_instructions, precautions, seed_price, availability, growing_difficulty) VALUES
('Holy Basil (Tulsi)', 'Ocimum tenuiflorum', 'Sacred Basil, Tulsi, Krishna Tulsi', 'Herb', 'Adaptogenic, Antimicrobial, Anti-inflammatory, Antioxidant', 'Stress relief, Immune support, Respiratory health, Blood sugar regulation', 'Sow seeds in well-drained soil. Keep soil moist but not waterlogged. Germination occurs in 7-14 days.', 'Warm, humid climate. Temperature range 20-35°C', 'Well-drained loamy soil with pH 6.0-7.5', 'Daily during dry periods, avoid overwatering', 'Full sun to partial shade (6-8 hours daily)', '60-90 days from planting', 'Leaves, Seeds, Flowers', 'Fresh consumption, Tea, Extract, Powder', '2-3 fresh leaves daily or 1 cup tea twice daily', 'Avoid during pregnancy. May interact with blood-thinning medications.', 25, 'Available', 'Easy'),
('Ashwagandha', 'Withania somnifera', 'Winter Cherry, Indian Ginseng, Poison Gooseberry', 'Shrub', 'Adaptogenic, Anxiolytic, Anti-inflammatory, Immunomodulatory', 'Stress management, Energy boost, Sleep improvement, Hormone balance', 'Sow seeds 1 cm deep in seed trays. Transplant after 4-6 weeks. Requires minimal care once established.', 'Dry climate preferred. Temperature range 20-30°C', 'Sandy loam with good drainage. pH 7.5-8.0', 'Minimal watering, drought tolerant once established', 'Full sun (8+ hours daily)', '150-180 days for roots', 'Roots, Leaves, Berries', 'Powder, Extract, Decoction, Capsules', '300-500mg root powder daily with milk or water', 'Avoid during pregnancy and breastfeeding. May interact with thyroid medications.', 45, 'Available', 'Medium'),
('Fenugreek', 'Trigonella foenum-graecum', 'Methi, Greek Hay, Birds Foot', 'Herb', 'Hypoglycemic, Galactagogue, Anti-inflammatory, Digestive', 'Blood sugar control, Lactation support, Digestive health, Cholesterol reduction', 'Direct sow seeds 1-2 cm deep. Thin seedlings to 10 cm apart. Cool season crop.', 'Cool, dry climate. Temperature range 15-25°C', 'Well-drained fertile soil. pH 6.0-7.0', 'Regular watering until establishment, then moderate', 'Full sun (6-8 hours daily)', '90-120 days for seeds, 30-40 days for leaves', 'Seeds, Leaves', 'Sprouted seeds, Powder, Tea, Cooked leaves', '1 tsp soaked seeds daily or fresh leaves as vegetable', 'May cause digestive upset in large quantities. Avoid if allergic to legumes.', 20, 'Available', 'Easy'),
('Brahmi', 'Bacopa monnieri', 'Water Hyssop, Herb of Grace, Indian Pennywort', 'Herb', 'Nootropic, Adaptogenic, Neuroprotective, Anti-anxiety', 'Memory enhancement, Cognitive function, Stress reduction, Mental clarity', 'Grows well in wet soil or shallow water. Can be grown in containers with regular watering.', 'Warm, humid climate. Temperature range 22-35°C', 'Moist, fertile soil or aquatic conditions', 'Keep constantly moist or in standing water', 'Partial shade to full sun', '60-90 days for continuous harvesting', 'Whole plant, Leaves', 'Fresh juice, Powder, Oil infusion, Tea', '1-2 tsp fresh juice or 300mg powder daily', 'May cause drowsiness. Start with small doses.', 35, 'Available', 'Medium'),
('Neem', 'Azadirachta indica', 'Indian Lilac, Margosa Tree, Nimba', 'Tree', 'Antimicrobial, Anti-inflammatory, Antifungal, Insecticidal', 'Skin health, Dental care, Immune support, Blood purification', 'Soak seeds overnight before planting. Grows slowly initially but becomes hardy. Needs space to grow.', 'Tropical to subtropical. Temperature range 21-32°C', 'Well-drained soil, tolerates poor soils. pH 6.2-7.0', 'Regular watering for first 2 years, then drought tolerant', 'Full sun', '3-5 years for significant harvest', 'Leaves, Bark, Seeds, Oil', 'Oil extraction, Powder, Decoction, Paste', '2-4 leaves daily or as directed by practitioner', 'Bitter taste. Avoid internal use during pregnancy.', 30, 'Available', 'Medium'),
('Aloe Vera', 'Aloe barbadensis', 'True Aloe, Medicinal Aloe, Burn Plant', 'Succulent', 'Anti-inflammatory, Wound healing, Moisturizing, Antimicrobial', 'Skin healing, Digestive health, Burns treatment, Hair care', 'Plant in well-draining soil. Water sparingly. Propagate from offsets rather than seeds for better results.', 'Warm, dry climate. Temperature range 18-27°C', 'Sandy, well-draining soil. pH 7.0-8.5', 'Water deeply but infrequently, allow soil to dry between waterings', 'Bright, indirect light to partial sun', '18-24 months for mature plants', 'Gel from leaves, Latex', 'Fresh gel, Juice, Powder, Topical application', '2-4 tablespoons gel daily or topical application as needed', 'Test for skin sensitivity. Avoid latex during pregnancy.', 40, 'Available', 'Easy'),
('Ginger', 'Zingiber officinale', 'Adrak, Common Ginger, Culinary Ginger', 'Rhizome', 'Anti-inflammatory, Digestive, Anti-nausea, Warming', 'Digestive aid, Nausea relief, Anti-inflammatory, Immune support', 'Plant rhizome pieces with buds in rich, moist soil. Provide warmth and humidity for sprouting.', 'Warm, humid climate. Temperature range 25-30°C', 'Rich, well-draining loamy soil. pH 5.5-6.5', 'Keep soil consistently moist but not waterlogged', 'Partial shade to filtered sunlight', '8-10 months for baby ginger, 12 months for mature', 'Rhizome (root), Young shoots', 'Fresh consumption, Tea, Juice, Powder, Oil', '1-3g fresh ginger daily or 1 cup ginger tea', 'May interact with blood thinners. Limit intake if taking medications.', 25, 'Available', 'Medium'),
('Mint', 'Mentha spicata', 'Spearmint, Pudina, Garden Mint', 'Herb', 'Digestive, Antispasmodic, Antimicrobial, Cooling', 'Digestive health, Respiratory relief, Oral health, Cooling effect', 'Easy to grow from seeds or cuttings. Spreads rapidly, consider container growing to control spread.', 'Temperate climate. Temperature range 15-25°C', 'Moist, fertile soil. pH 6.0-7.0', 'Keep soil consistently moist', 'Partial shade to full sun', '60-90 days for continuous harvesting', 'Leaves, Stems', 'Fresh consumption, Tea, Oil extraction, Dried leaves', 'Fresh leaves as needed or 1-2 cups tea daily', 'Generally safe. May cause heartburn in sensitive individuals.', 15, 'Available', 'Easy');

-- Insert sample yoga asanas
INSERT INTO yoga_asanas (name, sanskrit_name, category, difficulty_level, duration_minutes, step_instructions, benefits, precautions, contraindications, best_time, dosha_benefits, sequence_order, prerequisite_asanas, modifications, breathing_pattern) VALUES
('Mountain Pose', 'Tadasana', 'Standing Poses', 'Beginner', 2, 'Stand tall with feet hip-width apart, Distribute weight evenly on both feet, Engage leg muscles and lift kneecaps, Lengthen spine and reach crown toward ceiling, Relax shoulders away from ears, Breathe deeply and hold position', 'Improves posture, Builds foundation for all poses, Increases body awareness, Strengthens legs', 'Avoid if you have low blood pressure, Practice against wall if dizzy', 'Severe headache, Low blood pressure', 'Anytime', 'Balances all doshas, especially grounding for Vata', 1, '', 'Use wall support, Feet wider apart for balance', 'Natural deep breathing'),
('Downward Facing Dog', 'Adho Mukha Svanasana', 'Inversion', 'Beginner', 5, 'Start on hands and knees in table top position, Tuck toes under and lift hips up and back, Straighten legs as much as comfortable, Press palms firmly into ground, Create inverted V shape with body, Hold and breathe deeply', 'Strengthens arms and legs, Stretches hamstrings, Improves circulation, Calms nervous system', 'Avoid if pregnant (after first trimester), Modify if wrist issues', 'High blood pressure, Recent eye surgery, Severe carpal tunnel', 'Morning or evening', 'Cooling for Pitta, energizing for Kapha', 2, 'Mountain Pose', 'Use blocks under hands, Bend knees slightly, Forearm variation', 'Long, deep breaths through nose'),
('Warrior I', 'Virabhadrasana I', 'Standing Poses', 'Beginner', 3, 'Step left foot back about 3-4 feet, Turn left foot out 45 degrees, Square hips toward front of mat, Bend right knee over ankle, Raise arms overhead, Hold, then repeat on other side', 'Strengthens legs, Opens hips, Improves balance, Builds confidence', 'Avoid deep lunge if knee problems, Keep front knee aligned', 'Severe knee injury, High blood pressure (keep arms lower)', 'Morning for energy', 'Builds strength for Vata, grounds Pitta energy', 3, 'Mountain Pose', 'Use block under front thigh, Keep hands on hips, Back heel up', 'Strong, steady breathing'),
('Tree Pose', 'Vrikshasana', 'Balance Poses', 'Beginner', 2, 'Stand in Mountain Pose, Shift weight to left foot, Place right foot on inner left thigh or calf (never on knee), Press foot into leg and leg into foot, Bring palms together at heart center, Focus on fixed point for balance, Repeat on other side', 'Improves balance, Strengthens standing leg, Enhances concentration, Opens hips', 'Use wall support if needed, Never place foot on side of knee', 'Severe balance disorders, Recent leg injury', 'Morning for focus', 'Grounding for Vata, calming for Pitta', 4, 'Mountain Pose', 'Toe on ground heel on ankle, Use wall support, Keep hands on hips', 'Calm, steady breathing'),
('Childs Pose', 'Balasana', 'Restorative', 'Beginner', 5, 'Kneel on floor with big toes touching, Separate knees about hip-width apart, Sit back on heels, Fold forward bringing forehead to mat, Extend arms forward or rest by sides, Breathe deeply and relax', 'Calms nervous system, Stretches hips and thighs, Relieves stress, Aids digestion', 'Avoid if pregnant, Use pillow under head if needed', 'Severe knee injury, Recent abdominal surgery', 'Anytime, especially when tired', 'Very calming for Vata and Pitta', 10, '', 'Pillow between calves and thighs, Knees wider apart, Arms by sides', 'Natural, calming breath');
