
-- Insert sample recipe data (first 20 recipes)
INSERT INTO recipes (title, description, ingredients, instructions, prep_time, cook_time, servings, dosha_effects, thermal_effect, weight_effect, recommended_doshas, seasonal_suitability, difficulty_level, calories_per_serving, rating, rating_count, created_by) VALUES
('Golden Turmeric Milk', 'Traditional Ayurvedic bedtime drink for better sleep and immunity', '["1 cup warm milk", "1 tsp turmeric powder", "1/4 tsp ginger powder", "pinch of black pepper", "1 tsp ghee", "1 tsp honey"]', '["Heat milk gently", "Add turmeric and ginger", "Stir in ghee and black pepper", "Add honey when warm (not hot)", "Serve immediately"]', 5, 5, 1, '{"vata": "balancing", "pitta": "balancing", "kapha": "slightly increasing"}', 'heating', 'light', 'Vata, Pitta', 'Winter, Monsoon', 'Easy', 180, 4.8, 2547, 'Dr. Priya Sharma'),
('Kitchari Bowl', 'Complete Ayurvedic meal that balances all three doshas', '["1 cup basmati rice", "1/2 cup split mung dal", "1 tsp cumin seeds", "1 tsp coriander seeds", "1 inch ginger", "1 tsp turmeric", "2 tbsp ghee", "salt to taste", "4 cups water"]', '["Wash rice and dal separately", "Heat ghee, add cumin and coriander seeds", "Add ginger and turmeric", "Add rice, dal and water", "Cook for 25-30 minutes until soft", "Season with salt"]', 10, 30, 4, '{"vata": "balancing", "pitta": "balancing", "kapha": "balancing"}', 'neutral', 'medium', 'All Doshas', 'All seasons', 'Easy', 320, 4.7, 1829, 'Chef Ramesh Kumar'),
('Cooling Cucumber Raita', 'Refreshing yogurt-based side dish perfect for Pitta constitution', '["1 large cucumber", "1 cup fresh yogurt", "1 tsp roasted cumin powder", "2 tbsp mint leaves", "1 tsp black salt", "1 tsp regular salt"]', '["Grate cucumber and squeeze out excess water", "Whisk yogurt until smooth", "Mix cucumber with yogurt", "Add cumin powder and salts", "Garnish with mint leaves", "Chill before serving"]', 15, 0, 3, '{"vata": "slightly increasing", "pitta": "balancing", "kapha": "increasing"}', 'cooling', 'light', 'Pitta', 'Summer', 'Easy', 85, 4.5, 1234, 'Chef Meera Nair'),
('Warming Ginger Tea', 'Digestive tea that kindles agni and improves circulation', '["2 inch fresh ginger", "2 cups water", "1 tsp honey", "1/4 tsp cinnamon powder", "2-3 cardamom pods"]', '["Slice ginger thinly", "Boil water with ginger and spices", "Simmer for 10 minutes", "Strain the tea", "Add honey when warm", "Serve hot"]', 5, 15, 2, '{"vata": "balancing", "pitta": "slightly increasing", "kapha": "balancing"}', 'heating', 'light', 'Vata, Kapha', 'Winter, Monsoon', 'Easy', 25, 4.6, 987, 'Dr. Anjali Patel'),
('Spiced Lentil Soup', 'Protein-rich soup with digestive spices for optimal nutrition', '["1 cup red lentils", "1 tsp turmeric", "1 tsp cumin seeds", "1 tsp mustard seeds", "2 dry red chilies", "1 inch ginger", "2 tbsp coconut oil", "curry leaves", "salt", "3 cups water"]', '["Wash and cook lentils with turmeric", "Heat oil, add mustard and cumin seeds", "Add curry leaves, chilies, and ginger", "Pour over cooked lentils", "Season with salt", "Simmer for 10 minutes"]', 10, 25, 4, '{"vata": "balancing", "pitta": "neutral", "kapha": "slightly increasing"}', 'heating', 'medium', 'Vata', 'Winter, Monsoon', 'Medium', 180, 4.4, 756, 'Chef Suresh Menon');

-- Add sample doctors (first 10)
INSERT INTO doctors (name, qualification, specialization, experience_years, consultation_fee, rating, rating_count, languages, region, availability_hours, bio, is_verified, is_available, commission_rate) VALUES
('Dr. Priya Sharma', 'BAMS, MD (Ayurveda)', 'General Ayurveda', 12, 650, 4.8, 247, '["Hindi", "English", "Punjabi"]', 'Delhi', '9:00 AM - 6:00 PM', 'Experienced Ayurvedic physician specializing in constitutional assessment and lifestyle counseling.', TRUE, TRUE, 0.25),
('Dr. Ramesh Kumar', 'BAMS, PhD', 'Panchakarma Therapy', 18, 750, 4.9, 312, '["Hindi", "English", "Tamil"]', 'Chennai', '10:00 AM - 7:00 PM', 'Senior consultant with expertise in traditional panchakarma treatments and detoxification.', TRUE, TRUE, 0.25),
('Dr. Meera Nair', 'BAMS, MD (Dravyaguna)', 'Digestive Health', 8, 600, 4.7, 189, '["Malayalam", "English", "Hindi"]', 'Kochi', '8:00 AM - 5:00 PM', 'Specialist in digestive disorders and herbal medicine with focus on dietary modifications.', TRUE, TRUE, 0.25),
('Dr. Anjali Patel', 'BAMS, MD (Kayachikitsa)', 'Women Health', 15, 700, 4.8, 276, '["Gujarati", "Hindi", "English"]', 'Ahmedabad', '9:00 AM - 6:00 PM', 'Expert in women health issues including PCOS, fertility, and hormonal imbalances.', TRUE, TRUE, 0.25),
('Dr. Suresh Menon', 'BAMS, MD (Swasthavritta)', 'Preventive Medicine', 22, 800, 4.9, 398, '["Malayalam", "Tamil", "English"]', 'Bangalore', '10:00 AM - 8:00 PM', 'Pioneer in preventive Ayurveda and lifestyle medicine with expertise in yoga therapy.', TRUE, TRUE, 0.25),
('Dr. Kavitha Reddy', 'BAMS, MD (Panchakarma)', 'Detoxification', 10, 650, 4.6, 156, '["Telugu", "English", "Hindi"]', 'Hyderabad', '9:00 AM - 6:00 PM', 'Specializes in panchakarma detoxification programs and chronic disease management.', TRUE, TRUE, 0.25),
('Dr. Arjun Singh', 'BAMS, MD (Rasayana)', 'Anti-aging & Immunity', 14, 700, 4.8, 234, '["Hindi", "English", "Rajasthani"]', 'Jaipur', '8:00 AM - 5:00 PM', 'Expert in rasayana therapy for anti-aging and immunity building.', TRUE, TRUE, 0.25),
('Dr. Preeti Joshi', 'BAMS, MD (Manasroga)', 'Mental Wellness', 11, 750, 4.9, 187, '["Hindi", "English", "Marathi"]', 'Pune', '10:00 AM - 7:00 PM', 'Mental health specialist combining Ayurvedic psychology with modern approaches.', TRUE, TRUE, 0.25),
('Dr. Radha Krishnan', 'BAMS, PhD (Dravyaguna)', 'Herbal Medicine', 25, 850, 4.9, 456, '["Tamil", "English", "Sanskrit"]', 'Coimbatore', '9:00 AM - 6:00 PM', 'Renowned herbalist and researcher with deep knowledge of medicinal plants.', TRUE, TRUE, 0.25),
('Dr. Neha Gupta', 'BAMS, MD (Prasutitantra)', 'Maternal Health', 9, 650, 4.7, 167, '["Hindi", "English", "Haryanvi"]', 'Mumbai', '9:00 AM - 6:00 PM', 'Specialist in pregnancy care, childbirth, and postpartum recovery using Ayurvedic principles.', TRUE, TRUE, 0.25);
